# Generated by Django 4.2.11 on 2024-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('season', models.DecimalField(decimal_places=0, max_digits=8)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
        ),
    ]
