[build]
  command = "npm ci && npm install vite @vitejs/plugin-react && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20.5.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

