[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"


[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm install && npm run build"
