[build]
  base = "frontend" 
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/public"  # Adjust according to your build output


[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm install && npm run build"
