[build]
  base = "frontend"
  command = "npm install vite @vitejs/plugin-react && npm ci && npx vite build"
  publish = "frontend/dist"


[context.production.environment]
  NODE_VERSION = "20" # Specify the Node.js version you need
