[build]
  base = "frontend"
  command = "npm install --prefix . && npm run build --prefix ."
  publish = "public"  # Assuming 'public' is the output directory of your build

[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm install && npm run build"
