[build]
  base = "ratazana/"
  publish = "frontend/public"
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"


[build.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm install && npm run build --prefix frontend"
