# Generated by Django 5.1.1 on 2024-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='is_new_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jersey',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jersey',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jersey',
            name='season',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
