# Generated by Django 5.1.1 on 2024-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jersey_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
