# Generated by Django 5.1.1 on 2024-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_jersey_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
