# Generated by Django 5.1.1 on 2024-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jersey_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='image_url',
        ),
        migrations.AddField(
            model_name='jersey',
            name='image_path',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
