# Generated by Django 5.1.1 on 2024-09-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jersey_image_url_jersey_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='name',
        ),
    ]
