# Generated by Django 5.1.1 on 2024-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_jersey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='image_path',
            field=models.ImageField(upload_to='jerseys/'),
        ),
    ]
