# Generated by Django 5.1.1 on 2024-10-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_image_path_jersey_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jersey',
            old_name='image',
            new_name='image_path',
        ),
    ]
