# Generated by Django 5.1.1 on 2024-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_image_jerseyimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jersey',
            name='size',
            field=models.CharField(max_length=50, default='N/A'),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='brand',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='color',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='country',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='team',
            field=models.CharField(max_length=500),
        ),
    ]
