# Generated by Django 5.1.1 on 2024-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_image_jerseyimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default='N/A', max_digits=10),
        ),
        migrations.AddField(
            model_name='jersey',
            name='sizes',
            field=models.TextField(default='N/A'),
        ),
    ]
