# Generated by Django 5.1.1 on 2024-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_jersey_original_price_jersey_size_alter_jersey_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
