# Generated by Django 5.1.1 on 2024-10-04 08:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_jersey_original_price_alter_jersey_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
