# Generated by Django 5.1.1 on 2024-10-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_jersey_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jersey',
            old_name='size',
            new_name='sizes',
        ),
    ]
